# Generated by Django 4.0.4 on 2022-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
