# Generated by Django 4.0.4 on 2022-05-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_created_at_product_sold_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
